// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPwruBwviK2aG8eSM_1lsrCBwH2AFykcA',
    appId: '1:384031790723:web:337ca6dfdec17e38852db6',
    messagingSenderId: '384031790723',
    projectId: 'restockly-dev',
    authDomain: 'restockly-dev.firebaseapp.com',
    storageBucket: 'restockly-dev.firebasestorage.app',
    measurementId: 'G-6BP8ETZ180',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA09cRokoXfsoYsCcyCjFikjItN9KNpNM',
    appId: '1:384031790723:android:ec020cd9c2d30666852db6',
    messagingSenderId: '384031790723',
    projectId: 'restockly-dev',
    storageBucket: 'restockly-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyj1W1QL5emkAPjSY5jfV68BZfPPH8VvU',
    appId: '1:384031790723:ios:5b1afab19fa4cd0c852db6',
    messagingSenderId: '384031790723',
    projectId: 'restockly-dev',
    storageBucket: 'restockly-dev.firebasestorage.app',
    iosBundleId: 'com.example.restockly',
  );
}
